version: "3.2"
services:
  ibzrt-boot:
    image: ibiz4j/ibizlab-runtime
    ports:
      - "10086:10086"
    volumes:
      - $PWD:/app
    environment:
      - TZ=Asia/Shanghai
      - SERVER_PORT=10086
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos:8848
      - SPRING_DATASOURCE_USERNAME=a_LAB01_846b4aa81
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.16.186.185:3306/a_LAB01_846b4aa81?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
      - SPRING_DATASOURCE_DEFAULTSCHEMA=a_LAB01_846b4aa81
      - SPRING_REDIS_HOST=172.16.100.243
      - SPRING_REDIS_DATABASE=4
      - IBIZ_CACHELEVEL=L2
      - IBZ_SLEEP=30
      - IBIZ_SLEEP=30
      - JAVA_OPTS=-Xms256m -Xmx1024m
    depends_on:
      - nacos
    deploy:
      mode: replicated
      replicas: 1

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 512M

