version: "3.2"
services:
  ibzrt-boot:
    image: ibiz4j/ibizlab-runtime:1.0.14-RC1
    ports:
      - "10086:10086"
    networks:
      - agent_network
    volumes:
      - $PWD:/app
    environment:
      - TZ=Asia/Shanghai
      - SERVER_PORT=10086
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos:8848
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://ibzrt-db:3306/a_A_5d9d78509?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_REDIS_HOST=ibzrt-redis
      - IBIZ_CACHELEVEL=L2
      - IBZ_SLEEP=30
      - IBIZ_SLEEP=30
      - JAVA_OPTS=-Xms256m -Xmx1024m
    depends_on:
      - ibzrt-db
      - ibzrt-redis
      - nacos
    deploy:
      mode: replicated
      replicas: 1


  ibzrt-db:
    image: mysql:5.7.20
    volumes:
      - $PWD/../../../../ibzdb-data/:/var/lib/mysql/
    networks:
      - agent_network
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=a_A_5d9d78509
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

  ibzrt-redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
    command: redis-server
    networks:
      - agent_network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M

  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - agent_network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 512M


#  flowable-all-in-one-app:
#    image: flowable/all-in-one:6.4.2
#    volumes:
#      - $PWD/mysql-connector-java-8.0.18.jar:/opt/tomcat/lib/mysql-connector-java-8.0.18.jar
#    environment:
#      - SERVER_PORT=9977
#      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
#      - SPRING_DATASOURCE_URL=jdbc:mysql://ibzrt-db:3306/a_A_5d9d78509?useUnicode=true&characterEncoding=utf8&useSSL=false
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#      - FLOWABLE_COMMON_APP_IDM-REDIRECT-URL=http://127.0.0.1:8383/flowable-idm
#      - FLOWABLE_REST_APP_AUTHENTICATION-MODE=any-user
#    networks:
#      - agent_network
#    ports:
#      - 10080:8080
#    depends_on:
#      - ibzrt-db
#      - ibzrt-boot
#    deploy:
#      resources:
#        limits:
#          memory: 256M
#        reservations:
#          memory: 512M

networks:
  agent_network:
    attachable: true

