version: "3.2"
services:
  ibzrt-redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
    command: redis-server
    networks:
      - agent_network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - agent_network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 512M
networks:
  agent_network:
    attachable: true

