version: "3.2"
services:
  ibzrt-db:
    image: mysql:5.7.20
    volumes:
      - $PWD/../../../../ibzdb-data/:/var/lib/mysql/
    networks:
      - agent_network
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=a_A_5d9d78509
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
  ibzrt-redis:
    image: redis
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
    command: redis-server
    networks:
      - agent_network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - agent_network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 512M
networks:
  agent_network:
    attachable: true

