package cn.ibizlab.ou.logic.ibzemployeelogic.savedeptmember;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.core.ou.domain.IBZDeptMember ibzemployeesavedeptmembermember;
global cn.ibizlab.core.ou.domain.IBZEmployee ibzemployeesavedeptmemberdefault;
global cn.ibizlab.core.ou.service.IIBZDeptMemberService ibzdeptmemberservice;
global cn.ibizlab.core.ou.service.IIBZEmployeeService iBzSysIbzemployeeDefaultService;
global cn.ibizlab.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ibzemployeesavedeptmemberbegin"
    when
    then
    end

//逻辑处理节点[准备成员]
rule "prepareparam1"
ruleflow-group "ibzemployeesavedeptmemberprepareparam1"
    when
    then
    ibzemployeesavedeptmembermember.set("deptid",ibzemployeesavedeptmemberdefault.get("mdeptid"));
    ibzemployeesavedeptmembermember.set("userid",ibzemployeesavedeptmemberdefault.get("userid"));
    update(ibzemployeesavedeptmembermember);//更新fact中变量值
    update(ibzemployeesavedeptmemberdefault);//更新fact中变量值
    end

//逻辑处理节点[保存成员]
rule "deaction1"
ruleflow-group "ibzemployeesavedeptmemberdeaction1"
    when
    then
    ibzdeptmemberservice.save(ibzemployeesavedeptmembermember);
    update(ibzemployeesavedeptmembermember);//更新fact中变量值
    update(ibzemployeesavedeptmemberdefault);//更新fact中变量值
    end

