spring:
  profiles:
    include: sys , nacos, web-dev,  api-dev,  dev
  application:
    name: ibzuaa
  main:
    allow-bean-definition-overriding: true
zuul:
  routes:
    loginv7:
      path: /v7/login
      serviceId: ibzuaa-api
      stripPrefix: false