spring:
  profiles:
    include: sys , nacos, web-dev,  api-dev,  dev
  application:
    name: ibzuaa
  main:
    allow-bean-definition-overriding: true
zuul:
  routes:
    loginv7:
      path: /v7/login
      serviceId: ${ibiz.ref.service.ibzuaa-api:ibzuaa-api}
      stripPrefix: false
    wfcore:
      path: /wfcore/**
      serviceId: ${ibiz.ref.service.wf:ibzwf-api}
      stripPrefix: true
    disk:
      path: /net-disk/**
      serviceId: ${ibiz.ref.service.disk:ibzdisk-api}
      stripPrefix: false
  sensitive-headers:
  - Cookie,Set-Cookie,Authorization