---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibzdisk-provider-api
  labels:
    app: ibzdisk-provider-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibzdisk-provider-api
  template:
    metadata:
      labels:
        app: ibzdisk-provider-api
    spec:
      imagePullSecrets:
      - name: aly-shanghai
      containers:
      - name: ibzdisk-provider-api
        image: registry.cn-shanghai.aliyuncs.com/ibizsys/ibzdisk-provider-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 40006
        env:
        - name: SPRING_CLOUD_NACOS_DISCOVERY_IP
          value: "172.16.180.237"      
        - name: SERVER_PORT
          value: "40006"
        - name: SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR
          value: "172.16.100.243:8848"
        - name: SPRING_REDIS_HOST
          value: "172.16.100.243"
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: SPRING_REDIS_DATABASE
          value: "0"
        - name: SPRING_DATASOURCE_USERNAME
          value: "a_A_5d9d78509"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "@6dEfb3@"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://172.16.180.232:3306/a_A_5d9d78509?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&allowMultiQueries=true&serverTimezone=GMT%2B8"
        - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
          value: "com.mysql.jdbc.Driver"
        - name: SPRING_DATASOURCE_DEFAULTSCHEMA
          value: "a_A_5d9d78509"
        - name: NACOS
          value: "172.16.100.243:8848"      
        - name: SPRING_CLOUD_NACOS_DISCOVERY_GROUP
          value: "ibizdev"      
        volumeMounts:
        - name: data
          mountPath: /app/file
      volumes:      
      - name: data
        persistentVolumeClaim:
          claimName: demo-date-pvc-nfs

---
apiVersion: v1
kind: Service
metadata:
  name: ibzdisk-provider-api
  labels:
    app: ibzdisk-provider-api
spec:
  type: NodePort
  ports:
  - name: http
    port: 40006
    targetPort: 40006
    nodePort: 40006
    protocol: TCP
  selector:
    app: ibzdisk-provider-api

