version: "3.2"
services:
  ibznotify-provider-api:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ibznotify-provider-api:latest
    ports:
      - "8081:8081"
    networks:
      - agent_network
    deploy:
      resources:
           limits:
               memory: 4048M
           reservations:
               memory: 400M    
      mode: replicated
      replicas: 1
    volumes:
      - "nfs:/app/file"

volumes:
  nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=172.16.240.109,rw"
      device: ":/nfs"

networks:
  agent_network:
    driver: overlay
    attachable: true

