server:
  port: 30001
#Log配置
logging:
  level:
    cn.ibizlab: info
#zuul网关路由设置
zuul:
  routes:
    ibzdeptmember:
      path: /ibzdeptmembers/**
      serviceId: ibzou-api
      stripPrefix: false
    ibzteammember:
      path: /ibzteammembers/**
      serviceId: ibzou-api
      stripPrefix: false
    ibzdept:
      path: /ibzdepartments/**
      serviceId: ibzou-api
      stripPrefix: false
    ibzemp:
      path: /ibzemployees/**
      serviceId: ibzou-api
      stripPrefix: false
    ibzorg:
      path: /ibzorganizations/**
      serviceId: ibzou-api
      stripPrefix: false
    ibzteam:
      path: /ibzteams/**
      serviceId: ibzou-api
      stripPrefix: false
    loginv7:
      path: /v7/login
      serviceId: ibzuaa-api
      stripPrefix: false
    uaa:
      path: /uaa/**
      serviceId: ibzuaa-api
      stripPrefix: false
    config:
      path: /config/**
      serviceId: ibzuaa-api
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
