package cn.ibizlab.ou.logic.sysdeptmemberlogic.savedeptmember;
import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
import org.springframework.util.StringUtils;
import org.springframework.util.ObjectUtils;
import cn.ibizlab.util.errors.BadRequestAlertException;
global cn.ibizlab.core.ou.domain.SysDeptMember sysdeptmembersavedeptmemberdefault;
global cn.ibizlab.core.ou.service.ISysDeptMemberService sysdeptmemberservice;
global cn.ibizlab.core.ou.service.ISysDeptMemberService iBzSysSysdeptmemberDefaultService;
global cn.ibizlab.util.security.AuthenticationUser curuser;


no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "sysdeptmembersavedeptmemberbegin"
    when
    then
    end

//逻辑处理节点[准备sysuser参数]
rule "prepareparam1"
ruleflow-group "sysdeptmembersavedeptmemberprepareparam1"
    when
    then
    sysdeptmembersavedeptmemberdefault.set("deptid",sysdeptmembersavedeptmemberdefault.get("mdeptid"));
    sysdeptmembersavedeptmemberdefault.set("deptname",sysdeptmembersavedeptmemberdefault.get("mdeptname"));
    update(sysdeptmembersavedeptmemberdefault);//更新fact中变量值
    end

//逻辑处理节点[保存部门用户]
rule "deaction1"
ruleflow-group "sysdeptmembersavedeptmemberdeaction1"
    when
    then
    sysdeptmemberservice.save(sysdeptmembersavedeptmemberdefault);
    update(sysdeptmembersavedeptmemberdefault);//更新fact中变量值
    end

