---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibzpay-app-web
  labels:
    app: ibzpay-app-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibzpay-app-web
  template:
    metadata:
      labels:
        app: ibzpay-app-web
    spec:
      imagePullSecrets:
      - name: aly-shanghai
      containers:
      - name: ibzpay-app-web
        image: registry.cn-shanghai.aliyuncs.com/ibizsys/ibzpay-app-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /app/file
      volumes:      
      - name: data
        persistentVolumeClaim:
          claimName: demo-date-pvc-nfs

---
apiVersion: v1
kind: Service
metadata:
  name: ibzpay-app-web
  labels:
    app: ibzpay-app-web
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 8080
    protocol: TCP
  selector:
    app: ibzpay-app-web

