server:
  port: 30000
#zuul网关路由设置
zuul:
  routes:
    sys_role_permission:
      path: /sysrolepermissions/**
      serviceId: ibzuaa-api
      stripPrefix: false
    sys_user:
      path: /sysusers/**
      serviceId: ibzuaa-api
      stripPrefix: false
    sys_authlog:
      path: /sysauthlogs/**
      serviceId: ibzuaa-api
      stripPrefix: false
    wf_group_member:
      path: /wfmembers/**
      serviceId: ibzwf-api
      stripPrefix: false
    wf_user:
      path: /wfusers/**
      serviceId: ibzwf-api
      stripPrefix: false
    ibzorg:
      path: /ibzorganizations/**
      serviceId: ibzou-api
      stripPrefix: false
    wf_group:
      path: /wfgroups/**
      serviceId: ibzwf-api
      stripPrefix: false
    wf_model:
      path: /wfremodels/**
      serviceId: ibzwf-api
      stripPrefix: false
    sys_user_role:
      path: /sysuserroles/**
      serviceId: ibzuaa-api
      stripPrefix: false
    wf_definition:
      path: /wfprocessdefinitions/**
      serviceId: ibzwf-api
      stripPrefix: false
    sys_role:
      path: /sysroles/**
      serviceId: ibzuaa-api
      stripPrefix: false
    ibzdeptmember:
      path: /ibzdeptmembers/**
      serviceId: ibzou-api
      stripPrefix: false
    ibzdept:
      path: /ibzdepartments/**
      serviceId: ibzou-api
      stripPrefix: false
    sys_permission:
      path: /syspermissions/**
      serviceId: ibzuaa-api
      stripPrefix: false
    ibzemp:
      path: /ibzemployees/**
      serviceId: ibzou-api
      stripPrefix: false
    loginv7:
      path: /v7/login
      serviceId: ibzuaa-api
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
