/**
 * Index 部件模型
 *
 * @export
 * @class IndexModel
 */
export default class IndexModel {

    /**
     * 菜单项集合
     *
     * @public
     * @type {any[]}
     * @memberof IndexModel
     */
    public items: any[] = [
        {
	id: '1db61a83aabc731b610c9425f6071f6e',
	name: 'menuitem7',
	text: '单位人事',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '单位人事',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-th-large',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem7',
	items: [
		{
	id: 'dd13bb079489e883d7bec2d814eba421',
	name: 'menuitem1',
	text: '单位管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '单位管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-university',
	icon: '',
	textcls: '',
	appfunctag: 'Auto3',
	resourcetag: '',
	authtag:'Web-Index-menuitem1',
},
		{
	id: '5cd426f52054b0b2bbecd0f61088dff3',
	name: 'menuitem2',
	text: '部门管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '部门管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-sitemap',
	icon: '',
	textcls: '',
	appfunctag: 'Auto2',
	resourcetag: '',
	authtag:'Web-Index-menuitem2',
},
		{
	id: '61f3cc52ac218e3b5ea23df68906e2bd',
	name: 'menuitem3',
	text: '人员管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '人员管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-user',
	icon: '',
	textcls: '',
	appfunctag: 'Auto4',
	resourcetag: '',
	authtag:'Web-Index-menuitem3',
},
		{
	id: '16cb3dfc2d881822f50d40deac4ab40c',
	name: 'menuitem12',
	text: '岗位管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '岗位管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-cube',
	icon: '',
	textcls: '',
	appfunctag: 'Auto13',
	resourcetag: '',
	authtag:'Web-Index-menuitem12',
},
		{
	id: '38886fcfd4b7c5c9f41e096d5824bb3e',
	name: 'menuitem13',
	text: '组管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '组管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-group',
	icon: '',
	textcls: '',
	appfunctag: 'Auto9',
	resourcetag: '',
	authtag:'Web-Index-menuitem13',
},
	],
},
        {
	id: '3697b5425b8eb71efa809a9d3a30ff18',
	name: 'menuitem8',
	text: '系统权限',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '系统权限',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-cubes',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem8',
	items: [
		{
	id: '43e3576ee5e0ea4e4f584d6922f6d991',
	name: 'menuitem4',
	text: '用户角色',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '用户角色',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-unlock-alt',
	icon: '',
	textcls: '',
	appfunctag: 'Auto5',
	resourcetag: '',
	authtag:'Web-Index-menuitem4',
},
		{
	id: '86f4c21a46aedb9b9dcd319428cc6dba',
	name: 'menuitem9',
	text: '认证日志',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '认证日志',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-sort-amount-asc',
	icon: '',
	textcls: '',
	appfunctag: 'Auto6',
	resourcetag: '',
	authtag:'Web-Index-menuitem9',
},
		{
	id: 'f0015a0b0a2aa46cb7b099889ccbe700',
	name: 'menuitem21',
	text: '接入应用',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '接入应用',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-buysellads',
	icon: '',
	textcls: '',
	appfunctag: 'Auto15',
	resourcetag: '',
	authtag:'Web-Index-menuitem21',
},
		{
	id: '22f76572178c43e159c753dd2d68803f',
	name: 'menuitem22',
	text: '第三方认证',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '第三方认证',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-slack',
	icon: '',
	textcls: '',
	appfunctag: 'AppFunc',
	resourcetag: '',
	authtag:'Web-Index-menuitem22',
},
		{
	id: '0743bfa82a3c031f7396dd29af369a3a',
	name: 'menuitem23',
	text: '账户绑定',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '账户绑定',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-link',
	icon: '',
	textcls: '',
	appfunctag: 'AppFunc2',
	resourcetag: '',
	authtag:'Web-Index-menuitem23',
},
	],
},
        {
	id: '928644b157dd714741a8368189bfa0f6',
	name: 'menuitem10',
	text: '流程管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '流程管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-empire',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem10',
	items: [
		{
	id: '61aee9b93cbc4dd7f6a82665e1735b03',
	name: 'menuitem6',
	text: '流程定义',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '流程定义',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-random',
	icon: '',
	textcls: '',
	appfunctag: 'Auto8',
	resourcetag: '',
	authtag:'Web-Index-menuitem6',
},
		{
	id: '4f3312d793db8f4e8b4d7c915196c08e',
	name: 'menuitem5',
	text: '流程角色',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '流程角色',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-users',
	icon: '',
	textcls: '',
	appfunctag: 'Auto1',
	resourcetag: '',
	authtag:'Web-Index-menuitem5',
},
		{
	id: '96e483203d8865d3aff40e02393a6d89',
	name: 'menuitem11',
	text: '发布新流程',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '发布新流程',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-arrow-circle-o-up',
	icon: '',
	textcls: '',
	appfunctag: 'Auto7',
	resourcetag: '',
	authtag:'Web-Index-menuitem11',
},
	],
},
        {
	id: 'f5c8fcb77899ed12ec64afbc0cae965e',
	name: 'menuitem14',
	text: '任务管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '任务管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-tasks',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem14',
	items: [
		{
	id: 'df5482196a70a9cf29da9b857df48767',
	name: 'menuitem15',
	text: '注册',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '注册',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-gear',
	icon: '',
	textcls: '',
	appfunctag: 'Auto11',
	resourcetag: '',
	authtag:'Web-Index-menuitem15',
},
		{
	id: '6cdd077f2810ff23ba3b4142103a333e',
	name: 'menuitem16',
	text: '任务',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '任务',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-tasks',
	icon: '',
	textcls: '',
	appfunctag: 'Auto12',
	resourcetag: '',
	authtag:'Web-Index-menuitem16',
},
		{
	id: '717880940152313ec5c0cf038ed70878',
	name: 'menuitem17',
	text: '日志',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '日志',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-align-justify',
	icon: '',
	textcls: '',
	appfunctag: 'Auto14',
	resourcetag: '',
	authtag:'Web-Index-menuitem17',
},
	],
},
        {
	id: '50cbe52e6a446930a0af78bfa01fdcc8',
	name: 'menuitem18',
	text: '字典管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '字典管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-reorder',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem18',
	items: [
		{
	id: '4442771531bc2b45277d0ed13f6b8d57',
	name: 'menuitem19',
	text: '目录',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '目录',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-folder-open-o',
	icon: '',
	textcls: '',
	appfunctag: 'Auto10',
	resourcetag: '',
	authtag:'Web-Index-menuitem19',
},
		{
	id: '8459e35500245d7166b10ce4230df128',
	name: 'menuitem20',
	text: '字典项',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '字典项',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-stack-exchange',
	icon: '',
	textcls: '',
	appfunctag: 'Auto16',
	resourcetag: '',
	authtag:'Web-Index-menuitem20',
},
	],
},
        {
	id: 'A406ED59-10D8-4482-ACC9-D6E848088905',
	name: 'menuitem24',
	text: '消息通知',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '消息通知',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem24',
	items: [
		{
	id: 'B6F25A0B-B2C3-4291-968E-E311823C9550',
	name: 'menuitem25',
	text: '第三方平台',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '第三方平台',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '',
	textcls: '',
	appfunctag: 'AppFunc3',
	resourcetag: '',
	authtag:'Web-Index-menuitem25',
},
		{
	id: '25FB3FBA-6838-4953-AC4F-20C97C6A2F7B',
	name: 'menuitem26',
	text: '消息模板',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '消息模板',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '',
	textcls: '',
	appfunctag: 'AppFunc4',
	resourcetag: '',
	authtag:'Web-Index-menuitem26',
},
		{
	id: '1A480358-9C2E-45D7-AA3C-2A2B14C32E7D',
	name: 'menuitem27',
	text: '消息账户',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '消息账户',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '',
	textcls: '',
	appfunctag: 'AppFunc5',
	resourcetag: '',
	authtag:'Web-Index-menuitem27',
},
	],
},
        {
	id: '575A683B-752B-46E7-8F77-EF579FC9829A',
	name: 'menuitem28',
	text: '支付管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '支付管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem28',
	items: [
		{
	id: '0B8F512C-A6E7-4103-8DBD-F4594942E8A7',
	name: 'menuitem29',
	text: '支付交易',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '支付交易',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '',
	textcls: '',
	appfunctag: 'AppFunc6',
	resourcetag: '',
	authtag:'Web-Index-menuitem29',
},
		{
	id: 'D80F5DD5-ABE3-4265-A9A7-8A19BD81C6C3',
	name: 'menuitem30',
	text: '支付平台',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '支付平台',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '',
	textcls: '',
	appfunctag: 'AppFunc7',
	resourcetag: '',
	authtag:'Web-Index-menuitem30',
},
	],
},
    ];

	/**
	 * 应用功能集合
	 *
	 * @public
	 * @type {any[]}
	 * @memberof IndexModel
	 */
	public funcs: any[] = [
	];

    /**
     * 获取所有菜单项集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppMenuItems(): any[] {
        return this.items;
    }

    /**
     * 获取所有应用功能集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppFuncs(): any[] {
        return this.funcs;
    }
}