/**
 * Index 部件模型
 *
 * @export
 * @class IndexModel
 */
export default class IndexModel {

    /**
     * 菜单项集合
     *
     * @public
     * @type {any[]}
     * @memberof IndexModel
     */
    public items: any[] = [
        {
	id: '1db61a83aabc731b610c9425f6071f6e',
	name: 'menuitem7',
	text: '单位人事',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '单位人事',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-th-large',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem7',
	items: [
		{
	id: 'dd13bb079489e883d7bec2d814eba421',
	name: 'menuitem1',
	text: '单位管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '单位管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-university',
	icon: '',
	textcls: '',
	appfunctag: 'Auto3',
	resourcetag: '',
	authtag:'Web-Index-menuitem1',
},
		{
	id: '5cd426f52054b0b2bbecd0f61088dff3',
	name: 'menuitem2',
	text: '部门管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '部门管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-sitemap',
	icon: '',
	textcls: '',
	appfunctag: 'Auto2',
	resourcetag: '',
	authtag:'Web-Index-menuitem2',
},
		{
	id: '61f3cc52ac218e3b5ea23df68906e2bd',
	name: 'menuitem3',
	text: '人员管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '人员管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-user',
	icon: '',
	textcls: '',
	appfunctag: 'Auto4',
	resourcetag: '',
	authtag:'Web-Index-menuitem3',
},
		{
	id: '82D1195C-F432-4A14-89B6-5160A37BA079',
	name: 'menuitem12',
	text: '岗位管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '岗位管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-cube',
	icon: '',
	textcls: '',
	appfunctag: 'Auto13',
	resourcetag: '',
	authtag:'Web-Index-menuitem12',
},
		{
	id: 'B36FBF11-A3AC-4778-87E3-336697896302',
	name: 'menuitem13',
	text: '组管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '组管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-group',
	icon: '',
	textcls: '',
	appfunctag: 'Auto9',
	resourcetag: '',
	authtag:'Web-Index-menuitem13',
},
	],
},
        {
	id: '3697b5425b8eb71efa809a9d3a30ff18',
	name: 'menuitem8',
	text: '系统权限',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '系统权限',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-cubes',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem8',
	items: [
		{
	id: '43e3576ee5e0ea4e4f584d6922f6d991',
	name: 'menuitem4',
	text: '用户角色',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '用户角色',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-unlock-alt',
	icon: '',
	textcls: '',
	appfunctag: 'Auto5',
	resourcetag: '',
	authtag:'Web-Index-menuitem4',
},
		{
	id: '86f4c21a46aedb9b9dcd319428cc6dba',
	name: 'menuitem9',
	text: '认证日志',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '认证日志',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-sort-amount-asc',
	icon: '',
	textcls: '',
	appfunctag: 'Auto6',
	resourcetag: '',
	authtag:'Web-Index-menuitem9',
},
		{
	id: 'C40A209E-B7FA-47F3-8F81-78109D6430B4',
	name: 'menuitem21',
	text: '接入应用',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '接入应用',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-buysellads',
	icon: '',
	textcls: '',
	appfunctag: '_2',
	resourcetag: '',
	authtag:'Web-Index-menuitem21',
},
	],
},
        {
	id: '928644b157dd714741a8368189bfa0f6',
	name: 'menuitem10',
	text: '流程管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '流程管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-empire',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem10',
	items: [
		{
	id: '61aee9b93cbc4dd7f6a82665e1735b03',
	name: 'menuitem6',
	text: '流程定义',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '流程定义',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-random',
	icon: '',
	textcls: '',
	appfunctag: 'Auto8',
	resourcetag: '',
	authtag:'Web-Index-menuitem6',
},
		{
	id: '4f3312d793db8f4e8b4d7c915196c08e',
	name: 'menuitem5',
	text: '流程角色',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '流程角色',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-users',
	icon: '',
	textcls: '',
	appfunctag: 'Auto1',
	resourcetag: '',
	authtag:'Web-Index-menuitem5',
},
		{
	id: '96e483203d8865d3aff40e02393a6d89',
	name: 'menuitem11',
	text: '发布新流程',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '发布新流程',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-arrow-circle-o-up',
	icon: '',
	textcls: '',
	appfunctag: 'Auto7',
	resourcetag: '',
	authtag:'Web-Index-menuitem11',
},
	],
},
        {
	id: '63FF60A2-D212-49EA-AF2D-B8BDB94DEF75',
	name: 'menuitem14',
	text: '任务管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '任务管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-tasks',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem14',
	items: [
		{
	id: '461C8EA9-5A62-4807-9D6C-216FDCA74866',
	name: 'menuitem15',
	text: '注册',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '注册',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-gear',
	icon: '',
	textcls: '',
	appfunctag: 'Auto11',
	resourcetag: '',
	authtag:'Web-Index-menuitem15',
},
		{
	id: 'E3DA2935-6AD1-4B22-99B0-0CEFB6E98D03',
	name: 'menuitem16',
	text: '任务',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '任务',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-tasks',
	icon: '',
	textcls: '',
	appfunctag: 'Auto12',
	resourcetag: '',
	authtag:'Web-Index-menuitem16',
},
		{
	id: '7A1F333E-ED1C-4C39-A52E-E32C3FE36F7A',
	name: 'menuitem17',
	text: '日志',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '日志',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-align-justify',
	icon: '',
	textcls: '',
	appfunctag: 'Auto14',
	resourcetag: '',
	authtag:'Web-Index-menuitem17',
},
	],
},
        {
	id: 'EB358659-A327-4195-9B88-0ABBED324F1E',
	name: 'menuitem18',
	text: '字典管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '字典管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-reorder',
	icon: '',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'Web-Index-menuitem18',
	items: [
		{
	id: '93B39387-4DF9-4B87-B8E6-99B2F0759268',
	name: 'menuitem19',
	text: '目录',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '目录',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-folder-open-o',
	icon: '',
	textcls: '',
	appfunctag: 'Auto10',
	resourcetag: '',
	authtag:'Web-Index-menuitem19',
},
		{
	id: 'B24E45E8-5D6D-45A3-92D7-19E8EBDF476D',
	name: 'menuitem20',
	text: '字典项',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '字典项',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: 'fa fa-stack-exchange',
	icon: '',
	textcls: '',
	appfunctag: '_3',
	resourcetag: '',
	authtag:'Web-Index-menuitem20',
},
	],
},
    ];

	/**
	 * 应用功能集合
	 *
	 * @public
	 * @type {any[]}
	 * @memberof IndexModel
	 */
	public funcs: any[] = [
	];

    /**
     * 获取所有菜单项集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppMenuItems(): any[] {
        return this.items;
    }

    /**
     * 获取所有应用功能集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppFuncs(): any[] {
        return this.funcs;
    }
}