server:
  port: 30003
#Log配置
logging:
  level:
    cn.ibizlab: info
#zuul网关路由设置
zuul:
  routes:
    wf_model:
      path: /wfremodels/**
      serviceId: ${ibiz.ref.service.ibzwf-api:ibzwf-api}
      stripPrefix: false
    wf_group_member:
      path: /wfmembers/**
      serviceId: ${ibiz.ref.service.ibzwf-api:ibzwf-api}
      stripPrefix: false
    wf_group:
      path: /wfgroups/**
      serviceId: ${ibiz.ref.service.ibzwf-api:ibzwf-api}
      stripPrefix: false
    wf_user:
      path: /wfusers/**
      serviceId: ${ibiz.ref.service.ibzwf-api:ibzwf-api}
      stripPrefix: false
    wf_definition:
      path: /wfprocessdefinitions/**
      serviceId: ${ibiz.ref.service.ibzwf-api:ibzwf-api}
      stripPrefix: false
    wf_pssystem:
      path: /wfsystems/**
      serviceId: ${ibiz.ref.service.ibzwf-api:ibzwf-api}
      stripPrefix: false
    loginv7:
      path: /v7/login
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
      stripPrefix: false
    changepwd:
      path: /v7/changepwd
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
      stripPrefix: false
    uaa:
      path: /uaa/**
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
      stripPrefix: false
    config:
      path: /config/**
      serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
      stripPrefix: false
    oucore:
      path: /ibzorganizations/**
      serviceId: ${ibiz.ref.service.ou:ibzou-api}
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
