spring:
  profiles:
    include: sys ,nacos, web-prod
  application:
    name: ibzuaa-web
zuul:
  routes:
    loginv7:
      path: /v7/login
      serviceId: ${ibiz.ref.service.ibzuaa-api:ibzuaa-api}
      stripPrefix: false
    uaa:
      path: /uaa/**
      serviceId: ${ibiz.ref.service.ibzuaa-api:ibzuaa-api}
      stripPrefix: false
    config:
      path: /config/**
      serviceId: ${ibiz.ref.service.ibzuaa-api:ibzuaa-api}
      stripPrefix: false
    wfcore:
      path: /wfcore/**
      serviceId: ${ibiz.ref.service.wf:ibzwf-api}
      stripPrefix: true
    disk:
      path: /net-disk/**
      serviceId: ${ibiz.ref.service.disk:ibzdisk-api}
      stripPrefix: true