server:
  port: 8080

#zuul网关路由设置
zuul:
  routes:
      loginv7:
        path: /v7/login
        serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
        stripPrefix: false
      changepwd:
        path: /v7/changepwd
        serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
        stripPrefix: false
      uaa:
        path: /uaa/**
        serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
        stripPrefix: false
      config:
        path: /configs/**
        serviceId: ${ibiz.ref.service.uaa:ibzuaa-api}
        stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
