server:
  port: 30004
#Log配置
logging:
  level:
    cn.ibizlab: info
#zuul网关路由设置
zuul:
  routes:
    dict_catalog:
      path: /dictcatalogs/**
      serviceId: ibzdict-api
      stripPrefix: false
    dict_option:
      path: /dictoptions/**
      serviceId: ibzdict-api
      stripPrefix: false
    loginv7:
      path: /v7/login
      serviceId: ibzuaa-api
      stripPrefix: false
    changepwd:
      path: /v7/changepwd
      serviceId: ibzuaa-api
      stripPrefix: false
    uaa:
      path: /uaa/**
      serviceId: ibzuaa-api
      stripPrefix: false
    config:
      path: /config/**
      serviceId: ibzuaa-api
      stripPrefix: false
    oucore:
      path: /ibzorganizations/**
      serviceId: ibzou-api
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
