version: "3.2"
services:
  ibzuaa-app-web:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ibzuaa-app-web:latest
    ports:
      - "30002:30002"
    networks:
      - agent_network
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.16.180.237
      - SERVER_PORT=30002
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=127.0.0.1:8848
      - SPRING_REDIS_HOST=127.0.0.1
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_DATABASE=0
      - SPRING_DATASOURCE_USERNAME=a_A_5d9d78509
      - SPRING_DATASOURCE_PASSWORD=@6dEfb3@
      - SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/a_A_5d9d78509?useUnicode=true&characterEncoding=utf8&useSSL=false
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_DEFAULTSCHEMA=a_A_5d9d78509
      - ABC=1
      - DEC=2
    deploy:
      resources:
           limits:
               memory: 800M
           reservations:
               memory: 400M    
      mode: replicated
      replicas: 1
    volumes:
      - "nfs:/app/file"

volumes:
  nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=172.16.240.109,rw"
      device: ":/nfs"

networks:
  agent_network:
    driver: overlay
    attachable: true

