server:
  port: 40005

#zuul网关路由设置
zuul:
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization

logging:
  level:
    cn.ibizlab.core.task: info
ibiz:
  enablePermissionValid: false
  auth:
    service: IBZUSERService

    token:
      util: SimpleTokenUtil
spring:
  cloud:
    nacos:
      discovery:
        enabled: false
  redis:
    host: 127.0.0.1