version: "3.2"
services:
  ibzrt-app-web:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ibzrt-app-web:latest
    ports:
      - "30000:30000"
    networks:
      - agent_network
    logging:
      driver: loki
      options:
        loki-url: "http://172.16.240.111:3100/loki/api/v1/push"
        max-size: "50m"
        max-file: "10"    
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.16.180.237
      - SERVER_PORT=30000
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=172.16.100.243:8848
      - SPRING_REDIS_HOST=172.16.100.243
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_DATABASE=0
      - SPRING_DATASOURCE_USERNAME=a_A_5d9d78509
      - SPRING_DATASOURCE_PASSWORD=@6dEfb3@
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.16.180.232:3306/a_A_5d9d78509?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&allowMultiQueries=true
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_DEFAULTSCHEMA=a_A_5d9d78509
      - NACOS=172.16.100.243:8848
      - SPRING_CLOUD_NACOS_DISCOVERY_GROUP=ibizdev
    deploy:
      resources:
           limits:
               memory: 800M
           reservations:
               memory: 400M    
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    volumes:
      - "nfs:/app/file"

volumes:
  nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=172.16.240.109,rw"
      device: ":/nfs"

networks:
  agent_network:
    driver: overlay
    attachable: true

